[package]
name = "wolfram-client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.38"

wstp = "0.2.4"
wolfram-expr = "0.1.3"
wolfram-app-discovery = "0.4.0"